export const FETCH_LUNCH_PACKAGES_REQUEST = 'FETCH_LUNCH_PACKAGES_REQUEST'
export const FETCH_LUNCH_PACKAGES_SUCCESS = 'FETCH_LUNCH_PACKAGES_SUCCESS'
export const FETCH_LUNCH_PACKAGES_FAILURE = 'FETCH_LUNCH_PACKAGES_FAILURE'
